// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ertmoqjejofmroturrfu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVydG1vcWplam9mbXJvdHVycmZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwNTQyMzUsImV4cCI6MjA3MDYzMDIzNX0.evquKy0lH3-_MMMMIECjXsotR80yRN7JT0utbMibf_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});